[package]
name = "simple_binary"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.common]
path = "../common"
